// This file centralizes the project data, making it easy to update or fetch from an API later.
export const portfolioProjects = [
  {
    id: 1,
    title: 'Compact Urban Oasis',
    bhkType: '1BHK',
    style: 'Modern Minimalist',
    description: 'A serene 1BHK apartment maximizing space with smart storage and a neutral color palette.',
    imageUrl: 'https://images.unsplash.com/photo-1618220179428-22790b461013?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
  },
  {
    id: 2,
    title: 'The Professional\'s Pad',
    bhkType: '1BHK',
    style: 'Industrial Chic',
    description: 'Exposed brick and metal accents define this stylish and functional 1BHK for the modern professional.',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
  },
  {
    id: 3,
    title: 'Family First Living',
    bhkType: '2BHK',
    style: 'Contemporary Comfort',
    description: 'A warm and inviting 2BHK designed for family life, featuring a spacious living area and cozy bedrooms.',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
  },
  {
    id: 4,
    title: 'Scandinavian Dream',
    bhkType: '2BHK',
    style: 'Scandinavian',
    description: 'Light woods, clean lines, and a focus on functionality create a peaceful retreat in this 2BHK home.',
    imageUrl: 'https://images.unsplash.com/photo-1595526114035-0d45ed16433d?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
  },
  {
    id: 5,
    title: 'Entertainer\'s Paradise',
    bhkType: '3BHK',
    style: 'Luxury Modern',
    description: 'An expansive 3BHK with an open-plan kitchen and living area, perfect for hosting guests in style.',
    imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
  },
  {
    id: 6,
    title: 'Bohemian Rhapsody',
    bhkType: '2BHK',
    style: 'Bohemian',
    description: 'Rich textures, eclectic patterns, and a vibrant color scheme make this 2BHK a unique and artistic home.',
    imageUrl: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
  },
  {
    id: 7,
    title: 'The Executive Suite',
    bhkType: '3BHK',
    style: 'Elegant & Sophisticated',
    description: 'Dark wood tones, marble accents, and premium finishes create an atmosphere of luxury in this 3BHK residence.',
    imageUrl: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
  },
  {
    id: 8,
    title: 'Coastal Charm',
    bhkType: '3BHK',
    style: 'Coastal',
    description: 'A light and airy 3BHK that brings the tranquility of the beach indoors with blues, whites, and natural textures.',
    imageUrl: 'https://images.unsplash.com/photo-1567016432779-174826b856a9?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb',
  },
];
